### ISSUE TITLE
API taking too long to respond

### ISSUE THREAD

**Issue by VishalTheAries** [Mangopay/mangopay2-python-sdk#106]
```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~square-staging/1.400366027921119267/mysquare/handlers/debug.py", line 183, in get
    wallet =Wallet.get(20440920)
  File "/base/data/home/apps/s~square-staging/1.400366027921119267/mysquare/../lib/mangopay/resources.py", line 204, in get
    return super(Wallet, cls).get(*args, **kwargs)
  File "/base/data/home/apps/s~square-staging/1.400366027921119267/mysquare/../lib/mangopay/base.py", line 236, in get
    return cls.select().get(*args, **kwargs)
  File "/base/data/home/apps/s~square-staging/1.400366027921119267/mysquare/../lib/mangopay/query.py", line 56, in get
    result, data = handler.request(self.method, url)
  File "/base/data/home/apps/s~square-staging/1.400366027921119267/mysquare/../lib/mangopay/api.py", line 53, in request
    headers['Authorization'] = self.auth_manager.get_token()
  File "/base/data/home/apps/s~square-staging/1.400366027921119267/mysquare/../lib/mangopay/auth.py", line 92, in get_token
    auth_result = self.authorization.oauth_token()
  File "/base/data/home/apps/s~square-staging/1.400366027921119267/mysquare/../lib/mangopay/auth.py", line 119, in oauth_token
    oauth_request=True)
  File "/base/data/home/apps/s~square-staging/1.400366027921119267/mysquare/../lib/mangopay/api.py", line 83, in request
    headers=headers)
  File "/base/data/home/apps/s~square-staging/1.400366027921119267/mysquare/../lib/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/base/data/home/apps/s~square-staging/1.400366027921119267/mysquare/../lib/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/base/data/home/apps/s~square-staging/1.400366027921119267/mysquare/../lib/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/base/data/home/apps/s~square-staging/1.400366027921119267/mysquare/../lib/requests_toolbelt/adapters/appengine.py", line 122, in urlopen
    **response_kw)
  File "/base/data/home/apps/s~square-staging/1.400366027921119267/mysquare/../lib/requests/packages/urllib3/contrib/appengine.py", line 152, in urlopen
    raise TimeoutError(self, e)
TimeoutError: (<requests.packages.urllib3.contrib.appengine.AppEngineManager object at 0xfb990af0>, DeadlineExceededError('Deadline exceeded while waiting for HTTP response from URL: https://api.sandbox.mangopay.com/v2.01/oauth/token',))
```
We are facing the above error whevever we are trying to use the mangopay API seems like mangopay API's are taking huge time to respond due to which our system fails. Earlier everything was working smoothly. Please have a look as soon as possible

**Comment by mickaelpois** [comment]
Hello @VishalTheAries,
Could you tell us more details about this issue:
- apex time
- only on OAuth call?
- only in sandbox ?

I hope we could be helpful very soon !

Mickaël

**Comment by VishalTheAries** [comment]
Apex time is 5 seconds if a server streams one byte every 5 seconds, a timeout of 5 seconds will not be trigger, even if request will take several minutes to complete
Since every first call is followed by OAuth Call so i am not sure following request are working or not.
We are intergrating the environment so working on Sandbox only right now don't know of this is also a problem with production environmment

**Comment by mickaelpois** [comment]
Good morning @VishalTheAries,

Thanks for these infos. 
So, that is happening everytime for you since yesterday, each time you're trying to do an OAuth call, right?
Have you some precise hour to tell us about this issue, we will also take a look at requests that we received on Sandbox env.

Last, maybe you could send me your clientID (and only your clientID :) ) to do more precise searches about that.

Thanks a lot.

**Comment by VishalTheAries** [comment]
Hi,
my client ID is mysquare and yes it is first noticed by us yesterday only at around 10:00 am GMT

**Comment by mickaelpois** [comment]
Hello @VishalTheAries,

We are investigating but we can not find yet something that could be relevant.
I have made a comparison between calls that you were doing before and after 6th April 10 AM GMT, but can't see any difference, especially on time taken by the requests (less that 100 ms on our side).

Then, there is no complaints made by other clients, using or not Python API.
I've done mysself a request to our API on Sandbox env. and have an immediate response without any issue.
Please, could you check on your side that no changes have been done from April 6th?

Thanks a lot.
