### ISSUE TITLE
APIError responses with ConnnectionError

### ISSUE THREAD

**Issue by oziomek1** [Mangopay/mangopay2-python-sdk#305]
Hi,

I experience issues with the package returning frequently 
```python
mangopay.exceptions:APIError: ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

My setup: 
```sh
python3.8
mangopaysdk==3.17.0
django==3.0.11
```
`APIRequest` timeout is set to 30seconds.

The conditions under which the error appears are fairly similar.
My backend is connected to the mobile app. 
For requests that reach your API within a short period of time (regular app usage, within the timeout of 30sec), the error is not showing up. 
But if the time between requests is larger (much larger than timeout), the very first request often ends up with this requests library error.

I made a few updates to my code to avoid it, but neither fixed that. I read several threads/articles regarding the issue but had no luck in solving it. 
My assumptions are, that I experience some problems with the python requests package session, but don't know what exactly. My backends seem to be connecting to an already closed session or something similar.

The only remaining thing I didn't test is to retry SDK calls whenever this error appears, but I'd like to avoid it as much as possible.

Any help is much appreciated 🙏  I'm trying to figure it out for a few days already. 
I can share with you part of my code to investigate it further if possible. 

Below is a sample stacktrace I receive
```python
mangopay.exceptions:APIError: ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
File "/CUSTOM_APP_FILE", line 26, in post
File "/CUSTOM_APP_FILE", line 56, in create_wallets
File "CUSTOM_APP_FILE", line 33, in create_wallet
File "/CUSTOM_APP_FILE", line 63, in get_mgp_user_by_db_user
File "/usr/local/lib/python3.8/site-packages/mangopay/base.py", line 249, in get
File "/usr/local/lib/python3.8/site-packages/mangopay/query.py", line 56, in get
File "/usr/local/lib/python3.8/site-packages/mangopay/api.py", line 64, in request
File "/usr/local/lib/python3.8/site-packages/mangopay/api.py", line 78, in custom_request
File "/usr/local/lib/python3.8/site-packages/mangopay/auth.py", line 88, in get_token
File "/usr/local/lib/python3.8/site-packages/mangopay/auth.py", line 112, in oauth_token
File "/usr/local/lib/python3.8/site-packages/mangopay/api.py", line 64, in request
File "/usr/local/lib/python3.8/site-packages/mangopay/api.py", line 127, in custom_request
File "/usr/local/lib/python3.8/site-packages/mangopay/utils.py", line 860, in reraise_as
File "/usr/local/lib/python3.8/site-packages/six.py", line 718, in reraise
File "/usr/local/lib/python3.8/site-packages/mangopay/api.py", line 114, in custom_request
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
```

**Comment by fredericdelordm** [comment]
Hello @oziomek1, let us look into it

**Comment by SoloJr** [comment]
Hi @oziomek1 

I've tested on our end and we couldn't reproduce anything. Any updates from your side?

**Comment by oziomek1** [comment]
Hey, I'm almost certain, the error on my end.
I wasn't able to fix it entirely, but switching to the "retry-on-failure" approach seems to be good enough for me now. Thanks
