### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by alexei** [Mangopay/mangopay2-python-sdk#61]
There are a couple of tests that either fail with an error or don't pass

**Comment by alexei** [comment]
Thoughts?

**Comment by hobailey** [comment]
Hmm, there shouldn't be - could you specify which ones please?

**Comment by alexei** [comment]
Here's a dump:

```
======================================================================
ERROR: test_Clients_CreateClient (tests.testapiclients.Test_ApiClients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alexei/Projects/mangopay2-python-sdk/tests/testapiclients.py", line 16, in test_Clients_CreateClient
    client = self.sdk.clients.Create(id, 'test', 'test@o2.pl')
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/apiclients.py", line 29, in Create
    response = rest.Request(urlMethod, requestType, requestData)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 54, in Request
    return self.RequestIdempotent(None, urlMethod, requestType, requestData, pagination, additionalUrlParams)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 68, in RequestIdempotent
    response = self._runRequestIdempotent(idempotencyKey, urlMethod, pagination, additionalUrlParams)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 133, in _runRequestIdempotent
    self._checkResponseCode(response, decodedResp)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 177, in _checkResponseCode
    raise ResponseException(response.request.url, response.status_code, message)
ResponseException: One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error. Errors: [HeadquartersAddress: The HeadquartersAddress field is required.] [TechEmails: The TechEmails field is required.] [PlatformType: The PlatformType field is required.] [PlatformDescription: The PlatformDescription field is required.] [PlatformURL: The PlatformURL field is required.] 

======================================================================
ERROR: test_Users_GetKycDocuments (tests.testapiusers.Test_ApiUsers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alexei/Projects/mangopay2-python-sdk/tests/testapiusers.py", line 338, in test_Users_GetKycDocuments
    getKycDocuments = self.sdk.users.GetKycDocuments(user.Id, pagination)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/apiusers.py", line 280, in GetKycDocuments
    return self._getList('users_allkycdocuments', pagination, 'KycDocument', userId, None, sorting)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/apibase.py", line 301, in _getList
    response = rest.Request(urlMethod, self._getRequestType(methodKey), None, pagination, additionalUrlParams)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 54, in Request
    return self.RequestIdempotent(None, urlMethod, requestType, requestData, pagination, additionalUrlParams)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 68, in RequestIdempotent
    response = self._runRequestIdempotent(idempotencyKey, urlMethod, pagination, additionalUrlParams)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 133, in _runRequestIdempotent
    self._checkResponseCode(response, decodedResp)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 177, in _checkResponseCode
    raise ResponseException(response.request.url, response.status_code, message)
ResponseException: One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error. Errors: [page: The value 'None' is not valid for Int32.] 

======================================================================
ERROR: test_KycDocuments_GetAll (tests.testkycdocuments.Test_KycDocuments)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alexei/Projects/mangopay2-python-sdk/tests/testkycdocuments.py", line 17, in test_KycDocuments_GetAll
    list = self.sdk.kycdocuments.GetAll(pagination)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/apikycdocuments.py", line 12, in GetAll
    return self._getList('kyc_documents_all', pagination, 'KycDocument', None, None, sorting)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/apibase.py", line 301, in _getList
    response = rest.Request(urlMethod, self._getRequestType(methodKey), None, pagination, additionalUrlParams)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 54, in Request
    return self.RequestIdempotent(None, urlMethod, requestType, requestData, pagination, additionalUrlParams)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 68, in RequestIdempotent
    response = self._runRequestIdempotent(idempotencyKey, urlMethod, pagination, additionalUrlParams)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 133, in _runRequestIdempotent
    self._checkResponseCode(response, decodedResp)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 177, in _checkResponseCode
    raise ResponseException(response.request.url, response.status_code, message)
ResponseException: One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error. Errors: [page: The value 'None' is not valid for Int32.] 

======================================================================
ERROR: test_Idempotency (tests.testidempotency.Test_Idempotency)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alexei/Projects/mangopay2-python-sdk/tests/testidempotency.py", line 34, in test_Idempotency
    payOut = self.sdk.payOuts.CreateIdempotent(key, payOutPost)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/apipayouts.py", line 22, in CreateIdempotent
    return self._createObjectIdempotent(idempotencyKey, 'payouts_' + paymentKey + '_create', payOut, 'PayOut')
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/apibase.py", line 255, in _createObjectIdempotent
    response = rest.RequestIdempotent(idempotencyKey, urlMethod, self._getRequestType(methodKey), requestData)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 68, in RequestIdempotent
    response = self._runRequestIdempotent(idempotencyKey, urlMethod, pagination, additionalUrlParams)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 128, in _runRequestIdempotent
    response = self._sendRequest(request)
  File "/Users/alexei/Projects/mangopay2-python-sdk/mangopaysdk/tools/resttool.py", line 110, in _sendRequest
    prepared_request = request.prepare()
  File "/Users/alexei/.virtualenvs/mangopay/lib/python2.7/site-packages/requests/models.py", line 251, in prepare
    hooks=self.hooks,
  File "/Users/alexei/.virtualenvs/mangopay/lib/python2.7/site-packages/requests/models.py", line 295, in prepare
    self.prepare_headers(headers)
  File "/Users/alexei/.virtualenvs/mangopay/lib/python2.7/site-packages/requests/models.py", line 409, in prepare_headers
    check_header_validity(header)
  File "/Users/alexei/.virtualenvs/mangopay/lib/python2.7/site-packages/requests/utils.py", line 800, in check_header_validity
    "not %s" % (value, type(value)))
InvalidHeader: Header value 133325951085219544 must be of type str or bytes, not <type 'int'>

======================================================================
FAIL: test_Users_BankAccounts (tests.testapiusers.Test_ApiUsers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alexei/Projects/mangopay2-python-sdk/tests/testapiusers.py", line 255, in test_Users_BankAccounts
    self.assertTrue(pagination.TotalPages > 0)
AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by alexei** [comment]
I think I can fix the errors and also take a look at the failing one

**Comment by hobailey** [comment]
OK, thanks.

* test_Clients_CreateClient => This is missing the latest API updates regarding the client object but this call could be removed completely (due to the depreciation of this SDK, we most likely won't be updating this ourselves)
* test_Users_GetKycDocuments and test_KycDocuments_GetAll  => this doesn't seem normal and will require more debugging - if you wanted to take a look, that would be much appreciated
* test_Idempotency => This was passing when it was added - is it systematic?
* test_Users_BankAccounts => Likewise, this was passing when it was added - is it systematic?

**Comment by alexei** [comment]
Yeah, basically ever since I cloned the project I've seen these same errors

**Comment by hobailey** [comment]
Hmm, strange - well if you felt like fixing them, it would be hugely appreciated :-)

**Comment by hobailey** [comment]
Likewise, with the release of the new v3 version, we're no longer maintaining the previous versions so I'm closing this for now I'm afraid.
